name: Update README

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update the repo's README with recent github activity

    steps:
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
        with:
          COMMIT_MSG: '⚡ Update README with the recent activity'
          MAX_LINES: 5
